spring.application.name=udlaeats-core
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true